spring.application.name=auction_project

# ===================== DATABASE =====================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================== JPA/HIBERNATE =====================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.type.uuid_binary_strategy=standard

# ===================== JWT =====================
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}

# ===================== GOOGLE AUTH =====================
app.google.client-id=${GOOGLE_CLIENT_ID}

# ===================== REDIS =====================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.database=${REDIS_DATABASE}
spring.data.redis.connect-timeout=2000ms

# ===================== LOGGING =====================
logging.level.org.springframework.security=DEBUG